

export const _objects =  {
	"sEcho": "",
	"iTotalRecords": 12382,
	"iTotalDisplayRecords": 12382,
	"aaData": [
		{
			"ObjectId": 11429,
			"ObjectName": "на Советской",
			"ObjectAddress": "    Ростов-на-Дону, ул.Советская",
			"ObjectCoordinates": "47.2319727,39.7698458",
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "000 \"Сервис-Плюс\"",
			"DeviceGatewayName": "213.87.93.43:81",
			"DeviceGatewayId": 129516,
			"IsOnline": true,
			"AlarmsCount": 1,
			"AllDeviceCount": null as number,
			"OfflineDeviceCount": null as number
		},
		{
			"ObjectId": 11512,
			"ObjectName": "modem",
			"ObjectAddress": "    Киров",
			"ObjectCoordinates": "55.7549306,37.6091353",
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "4263_SC",
			"DeviceGatewayName": "ывапвпа",
			"DeviceGatewayId": 129468,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11512,
			"ObjectName": "modem",
			"ObjectAddress": "    Киров",
			"ObjectCoordinates": "55.7549306,37.6091353",
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "4263_SC",
			"DeviceGatewayName": "вапвыап",
			"DeviceGatewayId": 129469,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11558,
			"ObjectName": "Объект_02",
			"ObjectAddress": "    aa",
			"ObjectCoordinates": "56.2213136,51.083109050000004",
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "4263_SC",
			"DeviceGatewayName": "62.105.48.1",
			"DeviceGatewayId": 127948,
			"IsOnline": false,
			"AlarmsCount": 5,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11628,
			"ObjectName": "дляНАУЧНО-ТЕХНИЧЕСКИЙ ЦЕНТРА \"ЭЛЕКТРОЦЕНТРОМОНТАЖ\"",
			"ObjectAddress": "    Киров",
			"ObjectCoordinates": null,
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "4263_SC",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 29899,
			"ObjectName": "для Волгограда",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "4263_SC",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30241,
			"ObjectName": "!Продуктив",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "",
			"DeviceGatewayName": "81.195.232.205:80",
			"DeviceGatewayId": 128336,
			"IsOnline": true,
			"AlarmsCount": 4,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30898,
			"ObjectName": "test",
			"ObjectAddress": "    москва",
			"ObjectCoordinates": null,
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30899,
			"ObjectName": "а",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 33217,
			"ObjectName": "Для волгограда",
			"ObjectAddress": "Россия, Волгоград, Ул Героев Тулы",
			"ObjectCoordinates": "48.8380579,44.6463078",
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 33218,
			"ObjectName": "55555555555555",
			"ObjectAddress": "Волгоград, ",
			"ObjectCoordinates": "48.70813917090468,44.51534092426301",
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "\"Уралсервис\"",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 33222,
			"ObjectName": "1",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "\"Уралсервис\"",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 33254,
			"ObjectName": "Объект",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 320,
			"Domain": " ООО \"Сибирское здоровье\"",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11722,
			"ObjectName": "00001-object",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 527,
			"Domain": "00001-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "00001",
			"DeviceGatewayId": 79987,
			"IsOnline": true,
			"AlarmsCount": 7,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30016,
			"ObjectName": "004968-object",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 789,
			"Domain": "004968-company",
			"ServiceCompany": "",
			"DeviceGatewayName": "004968",
			"DeviceGatewayId": 105729,
			"IsOnline": true,
			"AlarmsCount": 7,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30048,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 805,
			"Domain": "005242",
			"ServiceCompany": "",
			"DeviceGatewayName": "005242-ecl4",
			"DeviceGatewayId": 105786,
			"IsOnline": true,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30048,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 805,
			"Domain": "005242",
			"ServiceCompany": "",
			"DeviceGatewayName": "005242-smd",
			"DeviceGatewayId": 105787,
			"IsOnline": true,
			"AlarmsCount": 2,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30048,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 805,
			"Domain": "005242",
			"ServiceCompany": "",
			"DeviceGatewayName": "005242-mqtt",
			"DeviceGatewayId": 105785,
			"IsOnline": true,
			"AlarmsCount": 2,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30156,
			"ObjectName": "123",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 868,
			"Domain": "123",
			"ServiceCompany": "ООО \"Спектр\"",
			"DeviceGatewayName": "11.21.20.1",
			"DeviceGatewayId": 129379,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 33033,
			"ObjectName": "gateways",
			"ObjectAddress": "Москва, Романов переулок 4",
			"ObjectCoordinates": null,
			"DomainId": 3239,
			"Domain": "2309",
			"ServiceCompany": "\"Уралсервис\"",
			"DeviceGatewayName": "2309_1",
			"DeviceGatewayId": 129361,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 33033,
			"ObjectName": "gateways",
			"ObjectAddress": "Москва, Романов переулок 4",
			"ObjectCoordinates": null,
			"DomainId": 3239,
			"Domain": "2309",
			"ServiceCompany": "\"Уралсервис\"",
			"DeviceGatewayName": "maps",
			"DeviceGatewayId": 129362,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11573,
			"ObjectName": "Наименование объекта",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 413,
			"Domain": "2647 Частное предприятие \"Европейская электротехническая компания",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "trionix-2647",
			"DeviceGatewayId": 78722,
			"IsOnline": true,
			"AlarmsCount": 29,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11573,
			"ObjectName": "Наименование объекта",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 413,
			"Domain": "2647 Частное предприятие \"Европейская электротехническая компания",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "192.168.1.55",
			"DeviceGatewayId": 78734,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11457,
			"ObjectName": "modem taewdrtfhuiojpotyr",
			"ObjectAddress": "    г. Волгоград, ул. Рокоссовского 62, 20-28 hjuokp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retytkp9urt retyt",
			"ObjectCoordinates": "48.73717,44.52993",
			"DomainId": 330,
			"Domain": "3081 3081 3081 3081 3081 3",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "3081",
			"DeviceGatewayId": 78510,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11500,
			"ObjectName": "test1",
			"ObjectAddress": "    г. Ростов-на-Дону, ул. Ленина, д.15",
			"ObjectCoordinates": "54.0635653,34.29268055",
			"DomainId": 330,
			"Domain": "3081 3081 3081 3081 3081 3",
			"ServiceCompany": "\"Уралсервис\"",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11501,
			"ObjectName": "test2",
			"ObjectAddress": "    Россия, Московская область,  д. Лешково",
			"ObjectCoordinates": "48.7298666,44.52510376206577",
			"DomainId": 330,
			"Domain": "3081 3081 3081 3081 3081 3",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "1 2 3",
			"DeviceGatewayId": 127740,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11501,
			"ObjectName": "test2",
			"ObjectAddress": "    Россия, Московская область,  д. Лешково",
			"ObjectCoordinates": "48.7298666,44.52510376206577",
			"DomainId": 330,
			"Domain": "3081 3081 3081 3081 3081 3",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "1.2.2.2",
			"DeviceGatewayId": 78552,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11501,
			"ObjectName": "test2",
			"ObjectAddress": "    Россия, Московская область,  д. Лешково",
			"ObjectCoordinates": "48.7298666,44.52510376206577",
			"DomainId": 330,
			"Domain": "3081 3081 3081 3081 3081 3",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "modem1",
			"DeviceGatewayId": 78784,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 4791,
			"ObjectName": "gateways",
			"ObjectAddress": "    Волгоград ул. Восточная 7 (Красноокт., Ворошиловский)",
			"ObjectCoordinates": "48.7181175,44.4612236",
			"DomainId": 293,
			"Domain": "3102 3102 310231023102310",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "trionix-3102",
			"DeviceGatewayId": 72448,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11458,
			"ObjectName": "modem",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 331,
			"Domain": "3115 FC",
			"ServiceCompany": "NAME131",
			"DeviceGatewayName": "3115",
			"DeviceGatewayId": 78517,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11576,
			"ObjectName": "3294 object",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 415,
			"Domain": "3294 company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "150ecl4",
			"DeviceGatewayId": 127767,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11576,
			"ObjectName": "3294 object",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 415,
			"Domain": "3294 company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "150smd",
			"DeviceGatewayId": 127768,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11576,
			"ObjectName": "3294 object",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 415,
			"Domain": "3294 company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "trionix-3294",
			"DeviceGatewayId": 78737,
			"IsOnline": true,
			"AlarmsCount": 20,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11576,
			"ObjectName": "3294 object",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 415,
			"Domain": "3294 company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "192.10.1.50",
			"DeviceGatewayId": 78745,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11576,
			"ObjectName": "3294 object",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 415,
			"Domain": "3294 company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "192.10.1.51",
			"DeviceGatewayId": 78748,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11576,
			"ObjectName": "3294 object",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 415,
			"Domain": "3294 company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "150mqtt",
			"DeviceGatewayId": 127766,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11471,
			"ObjectName": "modem",
			"ObjectAddress": "    г Волгоград Рокоссовского 62",
			"ObjectCoordinates": "48.7298666,44.52510376206577",
			"DomainId": 343,
			"Domain": "3299329932993",
			"ServiceCompany": "",
			"DeviceGatewayName": "trionix-3299",
			"DeviceGatewayId": 78534,
			"IsOnline": true,
			"AlarmsCount": 26,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 33039,
			"ObjectName": "123",
			"ObjectAddress": "Москва, ",
			"ObjectCoordinates": "55.7504461,37.6174943",
			"DomainId": 343,
			"Domain": "3299329932993",
			"ServiceCompany": "\"Уралсервис\"",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 30112,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 844,
			"Domain": "3388",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "3388",
			"DeviceGatewayId": 105902,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11506,
			"ObjectName": "modem",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 360,
			"Domain": "3412",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11530,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 376,
			"Domain": "3578",
			"ServiceCompany": "",
			"DeviceGatewayName": "3578",
			"DeviceGatewayId": 78681,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11582,
			"ObjectName": "Очень длинное наименование объекта",
			"ObjectAddress": "    Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62Волгоград Рокоссовского 62",
			"ObjectCoordinates": "48.7298666,44.52510376206577",
			"DomainId": 421,
			"Domain": "3828 company",
			"ServiceCompany": "",
			"DeviceGatewayName": "trionix-3828",
			"DeviceGatewayId": 78755,
			"IsOnline": true,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11554,
			"ObjectName": "gateways-1",
			"ObjectAddress": "    Москва, Романов переулок 4",
			"ObjectCoordinates": "55.7549306,37.6091353",
			"DomainId": 397,
			"Domain": "3858",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "3858",
			"DeviceGatewayId": 78703,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11555,
			"ObjectName": "gateways-2",
			"ObjectAddress": "    Москва, Романов переулок 7",
			"ObjectCoordinates": null,
			"DomainId": 397,
			"Domain": "3858",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "192.38.58.139",
			"DeviceGatewayId": 78704,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11556,
			"ObjectName": "gateways-3",
			"ObjectAddress": "    Москва, Романов переулок 2 c1",
			"ObjectCoordinates": null,
			"DomainId": 397,
			"Domain": "3858",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "3858_3",
			"DeviceGatewayId": 78705,
			"IsOnline": true,
			"AlarmsCount": 32,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11578,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 417,
			"Domain": "3916",
			"ServiceCompany": "",
			"DeviceGatewayName": "213.87.11.66",
			"DeviceGatewayId": 80042,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11578,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 417,
			"Domain": "3916",
			"ServiceCompany": "",
			"DeviceGatewayName": "3916",
			"DeviceGatewayId": 78742,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11578,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 417,
			"Domain": "3916",
			"ServiceCompany": "",
			"DeviceGatewayName": "192.168.10.9",
			"DeviceGatewayId": 78743,
			"IsOnline": false,
			"AlarmsCount": 17,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11608,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 436,
			"Domain": "3989",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11553,
			"ObjectName": "gateways-1",
			"ObjectAddress": "    Москва, Романов переулок 4",
			"ObjectCoordinates": null,
			"DomainId": 396,
			"Domain": "3997",
			"ServiceCompany": "ррр",
			"DeviceGatewayName": "358104090185669",
			"DeviceGatewayId": 78702,
			"IsOnline": true,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11600,
			"ObjectName": "Объекта_02",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 430,
			"Domain": "4015",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11606,
			"ObjectName": "gateways",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 434,
			"Domain": "4049",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11663,
			"ObjectName": "4111 object",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 485,
			"Domain": "4111 company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "4111",
			"DeviceGatewayId": 79888,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11751,
			"ObjectName": "4135-object 1",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": "55.7823547,49.1242266",
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41351",
			"DeviceGatewayId": 80073,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11752,
			"ObjectName": "4135-object 2",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41352",
			"DeviceGatewayId": 80075,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11753,
			"ObjectName": "4135-object 3",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41353",
			"DeviceGatewayId": 80076,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11754,
			"ObjectName": "4135-object 4",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41354",
			"DeviceGatewayId": 80079,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11755,
			"ObjectName": "4135-object 5",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41355",
			"DeviceGatewayId": 80074,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11756,
			"ObjectName": "4135-object 6",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41357",
			"DeviceGatewayId": 80089,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11757,
			"ObjectName": "4135-object 7",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41358",
			"DeviceGatewayId": 80090,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11758,
			"ObjectName": "4135-object 8",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41356",
			"DeviceGatewayId": 80084,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11759,
			"ObjectName": "4135-object 9",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413510",
			"DeviceGatewayId": 80087,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11760,
			"ObjectName": "4135-object 10",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "41359",
			"DeviceGatewayId": 80086,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11762,
			"ObjectName": "4135-object 12",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413513",
			"DeviceGatewayId": 80088,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11763,
			"ObjectName": "4135-object 13",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413511",
			"DeviceGatewayId": 80082,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11764,
			"ObjectName": "4135-object 14",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413515",
			"DeviceGatewayId": 80080,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11765,
			"ObjectName": "4135-object 15",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413516",
			"DeviceGatewayId": 80081,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11766,
			"ObjectName": "4135-object 16",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413517",
			"DeviceGatewayId": 80085,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11767,
			"ObjectName": "4135-object 17",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413514",
			"DeviceGatewayId": 80078,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11768,
			"ObjectName": "4135-object 18",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413518",
			"DeviceGatewayId": 80077,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11769,
			"ObjectName": "4135-object 19",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "413519",
			"DeviceGatewayId": 80091,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11770,
			"ObjectName": "4135-object 20",
			"ObjectAddress": "    Казань",
			"ObjectCoordinates": null,
			"DomainId": 554,
			"Domain": "4135-company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11615,
			"ObjectName": "4149_O1",
			"ObjectAddress": "    Волгоград",
			"ObjectCoordinates": null,
			"DomainId": 444,
			"Domain": "4149",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11616,
			"ObjectName": "4149_O2",
			"ObjectAddress": "    Чита",
			"ObjectCoordinates": null,
			"DomainId": 444,
			"Domain": "4149",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11620,
			"ObjectName": "test_4201",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 449,
			"Domain": "4201",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "10.21.20.67",
			"DeviceGatewayId": 78844,
			"IsOnline": false,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11635,
			"ObjectName": "gateways",
			"ObjectAddress": "    Москва, Романов переулок 17",
			"ObjectCoordinates": null,
			"DomainId": 459,
			"Domain": "4204",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "4204",
			"DeviceGatewayId": 79861,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11775,
			"ObjectName": "4211 object",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 559,
			"Domain": "4211 company",
			"ServiceCompany": "_Best service company",
			"DeviceGatewayName": "4211",
			"DeviceGatewayId": 80102,
			"IsOnline": true,
			"AlarmsCount": 1,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11661,
			"ObjectName": "4259_O1",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 484,
			"Domain": "4259",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11681,
			"ObjectName": "4263_O1",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 502,
			"Domain": "4263-company",
			"ServiceCompany": "",
			"DeviceGatewayName": "4263",
			"DeviceGatewayId": 79925,
			"IsOnline": true,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		},
		{
			"ObjectId": 11637,
			"ObjectName": "4275_O1",
			"ObjectAddress": "",
			"ObjectCoordinates": null,
			"DomainId": 461,
			"Domain": "4275",
			"ServiceCompany": "",
			"DeviceGatewayName": "",
			"DeviceGatewayId": 0,
			"IsOnline": false,
			"AlarmsCount": 0,
			"AllDeviceCount": null,
			"OfflineDeviceCount": null
		}
	]
}

export const _states = [
	{id:1, name:'все'},
	{id:2, name:'в аварии'},
	{id:3, name:'в сети'},
	{id:4, name:'не в сети'},
]

export const _limits = [
	{id:1, name:'Показать 10 записей', value:10},
	{id:2, name:'Показать 25 записей', value:25},
	{id:3, name:'Показать 50 записей', value:50}
]